### ISSUE TITLE
Couldn't find a navigation object

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog-js-lite#101]
## Bug description

(Reposted for @trobbertze)

Hi

I am currently evaluating Posthog for a React Native app.

I am getting the same error as logged in this issue:

https://github.com/PostHog/posthog/issues/11880

What I have found is that in our app the NavigationContainer is not the highest order component (if I can call it that). It is wrapped in a SafeAreaProvider, SafeAreaView and SideMenu components.

If I remove these components and make the NavigationContainer the highest order component, then I do not get the error. But unfortunately my app requires those.

So my question is this, is it possible to have Posthog working when the NavigationContainer is not the highest order component?

## How to reproduce

1.
2.
3.

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

**Comment by trobbertze** [comment]
Hi

I've created 2 simple scenarios, both of them do not work.  I get the error: "Couldn't find navigation object. Is your component inside a screen in a navigator?"

`import React from 'react';
import {
  SafeAreaView,
  Text
} from 'react-native';

import { NavigationContainer } from '@react-navigation/native'
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'

import { PostHogProvider } from 'posthog-react-native'


const Page1 = () => (
  <SafeAreaView>
    <Text>
      Page1
    </Text>
  </SafeAreaView>
)

const Page2 = () => (
  <SafeAreaView>
    <Text>
      Page2
    </Text>
  </SafeAreaView>
)

const Tab = createBottomTabNavigator()

const App = () => {
  return (
    <PostHogProvider apiKey="<ph_project_api_key>" autocapture>
      <NavigationContainer> 
        <Tab.Navigator
          initialRouteName="Page1"
        >
          <Tab.Screen
            name="Page1"
            component={Page1}
            options={{
              tabBarLabel: 'Page1'
            }}
          />
          <Tab.Screen
            name="Page2"
            component={Page2}
            options={{
              tabBarLabel: 'Page2'
            }}
          />
        </Tab.Navigator>
      </NavigationContainer>
    </PostHogProvider>
  );
}

export default App;
`

`import React from 'react';
import {
  SafeAreaView,
  Text
} from 'react-native';

import { NavigationContainer } from '@react-navigation/native'
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'

import { PostHogProvider } from 'posthog-react-native'


const Page1 = () => (
  <SafeAreaView>
    <Text>
      Page1
    </Text>
  </SafeAreaView>
)

const Page2 = () => (
  <SafeAreaView>
    <Text>
      Page2
    </Text>
  </SafeAreaView>
)

const Tab = createBottomTabNavigator()

const App = () => {
  return (
    <NavigationContainer>
      <PostHogProvider apiKey="<ph_project_api_key>" autocapture> 
        <Tab.Navigator
          initialRouteName="Page1"
        >
          <Tab.Screen
            name="Page1"
            component={Page1}
            options={{
              tabBarLabel: 'Page1'
            }}
          />
          <Tab.Screen
            name="Page2"
            component={Page2}
            options={{
              tabBarLabel: 'Page2'
            }}
          />
        </Tab.Navigator>
      </PostHogProvider>
    </NavigationContainer>
  );
}

export default App;`

This is my package.json file

`{
  "name": "PostHogIssue",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.1",
    "@react-navigation/bottom-tabs": "^5.11.15",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.14.9",
    "posthog-react-native": "^2.7.1",
    "react": "18.2.0",
    "react-native": "0.71.6",
    "react-native-async-storage": "0.0.1",
    "react-native-device-info": "^10.8.0",
    "react-native-gesture-handler": "^2.10.0",
    "react-native-safe-area-context": "^4.5.1",
    "react-native-screens": "^3.20.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by benjackwhite** [comment]
Thanks for the extra context. I think I managed to reproduce and it comes down to the versions. If I downgrade the example project to React Navigation v5 then I get that error.

It _could_ be an issue with React Navigation itself. I see a [dead issue](https://github.com/react-navigation/react-navigation/issues/8538) where someone was complaining about the same thing...

The actual hook for tracking screen changes is relatively straightforward. Could you perhaps try something like `autocapture={{ captureScreens: false }}` and then implement your own minimal version of [our hook](https://github.com/PostHog/posthog-js-lite/blob/master/posthog-react-native/src/hooks/useNavigationTracker.ts).

It would be interesting to know if `const navigation = useNavigation()` ever works within a child component of the `NavigationContainer` as it does sound like it could be a bug in V5.

```

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by bradydowling** [comment]
Just in case anyone else runs into this, I wanted to add some clarity and a potential solution. The way [this comment](https://github.com/PostHog/posthog-js-lite/issues/101#issuecomment-1630768724) was composed made me wonder what "under" meant (i.e. whether it's closer to the base, or as a child). As I suspected, under would be like so:
```
<Navigation>
    <PostHogProvider>
        <blah>
    </PostHogProvider>
</Navigation>
```

That said, this was happening for me even when I had nested my `PostHogProvider` under my `Navigation`. For me the solution was to generate a new dev build (in Expo). So with my setup that was:

```
yarn eas build --profile development-simulator --platform ios
```

Though for you that may look different. The point is that I think the PostHog install command (included below for clarity) adds native modules so you need to make a new Expo dev build at that point.

PostHog install command:
```
expo install posthog-react-native expo-file-system expo-application expo-device expo-localization
```

**Comment by kdawgwilk** [comment]
I just upgraded to Expo 52 SDK which upgraded `expo-router` to v4 and `@react-navigation/native` to v7 and this is now broken for me as well.  This is my root layout:
```tsx
<ApolloProvider client={apolloClient}>
  <PostHogProvider
    client={posthog}
    autocapture={{
      captureScreens: true,
      captureLifecycleEvents: true,
    }}
  >
    <AuthProvider>
      <ThemeProvider value={DarkTheme}>
        <InitLayout />
      </ThemeProvider>
    </AuthProvider>
  </PostHogProvider>
</ApolloProvider>
```

**Comment by marandaneto** [comment]
Similar to https://github.com/PostHog/posthog-js-lite/issues/450
Please take a look at this issue and the related PR; it should resolve the issue.
If not, please raise a new issue.
