### ISSUE TITLE
Don't complain about "initAsync called twice" when hot reloading

### ISSUE THREAD

**Issue by statico** [PostHog/posthog-js-lite#114]
## Is your feature request related to a problem?

Similar to #113 — every time my React Native app is loaded, reloaded, or the base layout changes (we're using expo-router), PostHog throws up a giant warning:

> PostHog.initAsync called twice with the same apiKey. The first instance will be used.

It would be nice to disable this message when `__DEV__` is true.

Recoil, a state management library for React, had a similar behavior with singletons and hot reloading and solved this by allowing developers to add a `RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=false` setting: https://github.com/facebookexperimental/Recoil/issues/733

## Describe the solution you'd like

Some kind of setting, maybe in PostHogProvider, like `dangerouslyIgnoreReinitialization` or `iKnowWhatImDoing={__DEV__}` or something, that removes this warning.

## Describe alternatives you've considered

- Patching the package with `patch-package`

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [ ] posthog-react-native

## Additional context

<3

**Comment by hikchoi** [comment]
seconding this. pretty harmless, but it makes it hard to read other logs that I actually want to read :(

@statico are you still patching the package on your end or have you found any other workarounds?

**Comment by statico** [comment]
@hikchoi Yep, still patching this and a few other messages. Previously with `patch-package`, now with pnpm's built-in patcher.

**Comment by marandaneto** [comment]
Maybe the solution here is to patch the Router and not call `PostHog.initAsync` again when a hot reload just happened, you can do that via env. var. (similar to [113](https://github.com/PostHog/posthog-js-lite/issues/113)) or a global variable that survives hot reload.

We already do that [here](https://github.com/PostHog/posthog-js-lite/blob/a604f6a9b62c8a8b351b23797bda6566ec0366d0/posthog-react-native/src/PostHogProvider.tsx#L68-L69) but if the whole Provider gets recreated, this field is also gone, the solution would be to depend on an external global variable.

**Comment by edumana** [comment]
I was getting this error and solved it by putting PH provider at the very top of the `RootLayout`, and **moving everything to a new <App/> child component**. I had some auth states changing which were causing PH provider to reload. So my app now looks like this:

`const RootLayout = () => {
  return (
      <PostHogProvider
        autocapture={{
          captureScreens: false,
        }}
        apiKey={process.env.EXPO_PUBLIC_POSTHOG_API_KEY}
        options={{
          host: process.env.EXPO_PUBLIC_POSTHOG_HOST,
        }}
      >
        <App /> // <------ all child components with changing states 
      </PostHogProvider>
  );
};

export default RootLayout;`

**Comment by marandaneto** [comment]
Closed by https://github.com/PostHog/posthog-js-lite/pull/179
The warning is removed since it's not useful anyway, you can still do [this](https://github.com/PostHog/posthog-js-lite/issues/114#issuecomment-1892624084) to spare the recreation bits.
