### ISSUE TITLE
[posthog-node] Upgrade axios to 1.6.0

### ISSUE THREAD

**Issue by arvidboivie** [PostHog/posthog-js-lite#121]
## Bug description

axios 1.6.0 includes a fix for https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

posthog-node is currently on `^0.27.0`

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [x] posthog-node
- [ ] posthog-react-native

**Comment by benjackwhite** [comment]
Not sure if that vulnerability really affects us but happy to do the upgrade
