### ISSUE TITLE
OptIn not possible when enable=false

### ISSUE THREAD

**Issue by chfinst** [PostHog/posthog-js-lite#133]
## Bug description

_Please describe._

## How to reproduce

1. use a PostHogProvider with the option enable: false
2. call optIn() on the object returned from the usePostHog hook
3. Verify that no user events are posted to PostHog

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

**Comment by benjackwhite** [comment]
We have tests covering this logic and I can't reproduce. 

Can you confirm the output when running`posthog.debug()` and that if you start with `enable: true` you actually get events? Seems like something more likely off with your configuration

**Comment by chfinst** [comment]
If I start with `enable: true` I get events, and I am able to call optOut() and optIn() to stop and start sending events. The output from posthog.optIn() when `enabled: true` is `PostHog Debug capture Library is disabled. Not sending event. To re-enable, call posthog.enable()`. Where do I find the enable function?

**Comment by marandaneto** [comment]
@benjackwhite not sure if related but [similar](https://posthog.com/questions/enable-option-not-working-still-sending-events) question a few months ago.

The `enqueue()` method logs this message to the console, and not the `posthog.optIn()`, and the `enqueue()` method is called by all the `capture()` methods.

@chfinst that was a mistake in the logging (we'll fix it), the method `enable()` does not exist, try to call `optIn()` instead, does that work?

You can also check the status of the flag by calling the `optedOut()` method, if its `false`, you should see events coming in, if it's `false`, you should not see events coming in.

**Comment by chfinst** [comment]
@marandaneto Yes, I am calling `posthog.optIn()`. 

When adding log statements to the getPersistedProperty and setPersistedProperty methods I see that the opted_out is set to `false` when I call `posthog.optIn()` but always read as undefined. 

When I inspect async-storage in Flipper I see that the value is false.

**Comment by chfinst** [comment]
Think that I may have found the issue:

1. `false` is converted to `undefined` her: https://github.com/PostHog/posthog-js-lite/blob/master/posthog-react-native/src/posthog-rn.ts#L128
2. As value from 1 is `false`, `optoutOverride` will be used: https://github.com/PostHog/posthog-js-lite/blob/master/posthog-core/src/index.ts#L108
3. According to https://github.com/PostHog/posthog-js-lite/blob/master/posthog-core/src/index.ts#L89 `optoutOverride` is true when `enable: false`.

**Comment by marandaneto** [comment]
@benjackwhite was that an intentional behaviour somehow or just a bug? (since there's the `optoutOverride` etc, not sure if it's any back compatibility workaround)
@chfinst would you be willing to open a PR with the fix?
