### ISSUE TITLE
Expo universal app's web target should not use expo-file-system

### ISSUE THREAD

**Issue by whollacsek** [PostHog/posthog-js-lite#139]
## Bug description

We are integrating Posthog in our stack and ran into this case where the web target is not handled by the Posthog react-native library properly.

## How to reproduce

1. Create a Expo universal app
2. Build and run the web target
3. Error

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

**Comment by whollacsek** [comment]
Re-exporting through platform specific extensions https://docs.expo.dev/router/advanced/platform-specific-modules/#platform-specific-extensions seem to work, but it should be handled automatically by the lib.

**Comment by marandaneto** [comment]
Related to https://github.com/PostHog/posthog-js-lite/issues/18 as well.

**Comment by marandaneto** [comment]
Closing in favor of https://github.com/PostHog/posthog-js-lite/issues/140
