### ISSUE TITLE
React Native Web and `expo-file-system` support

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-js-lite#140]
### Description

https://github.com/necolas/react-native-web#readme

RN Web is getting more popular but our SDK does not support it yet, at least not without workarounds.

The goal of this issue is to list all the issues encountered and at least make the changes to run the SDK on RN Web without any compile/runtime issues, even if some features have to be disabled.

Issues faced as of now:

* https://github.com/PostHog/posthog-js-lite/issues/139
* https://github.com/PostHog/posthog-js-lite/issues/18
* https://posthog.com/questions/the-method-or-property-expo-file-system-write-as-string-async-is-not-available-on-web

**Comment by saulamsal** [comment]
Is there an estimated timeline for this?

**Comment by marandaneto** [comment]
@saulamsal not planned yet, but please upvote the issue to gather interest.

Fixing the compile/runtime issues by disabling a few features should be doable though, would you like to give it a try with my guidance? happy to guide/review.

**Comment by marandaneto** [comment]
A quick workaround, for now, is to just call the [API directly](https://posthog.com/tutorials/api-capture-events) until we provide first-class support for React Native Web.

**Comment by saulamsal** [comment]
@marandaneto, I think I will just create a simple wrapper for RN Web with an API for now. Hopefully, you guys have a plan to work on it.

**Comment by marandaneto** [comment]
When using [async-storage](https://github.com/react-native-async-storage/async-storage/releases/tag/v1.9.0) instead of `expo-file-system`, almost everything works out of the box, the problem is only with `expo-file-system` since it does not support the Web target.

<img width="1604" alt="Screenshot 2024-01-22 at 11 32 48" src="https://github.com/PostHog/posthog-js-lite/assets/5731772/78c81843-8322-433a-b086-3948d8b55e2a">
