### ISSUE TITLE
`Application Became Active` event on RN should have been `Application Opened` with `from_background=true` property

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-js-lite#144]
### Description

* [Code](https://github.com/PostHog/posthog-js-lite/blob/4b24090d063e8b9472860f1ad0af7c1c6a21b4d8/posthog-react-native/src/hooks/useLifecycleTracker.ts#L16-L25) and [here](https://github.com/PostHog/posthog-js-lite/blob/01fff0242a620345614a792379397029cf6cc9f1/posthog-react-native/src/posthog-rn.ts#L239-L250).
* [Docs](https://posthog.com/docs/libraries/react-native#autocapture)

RN has a specific event called `Application Became Active` when the app is [active](https://reactnative.dev/docs/appstate#app-states) which means the app is back in the foreground.
On the other Mobile SDKs, we just capture the `Application Opened` event with the `from_background=true` property instead.

Ideally, we'd align this behavior in one way or the other.

When mobile dashboard templates are shipped, templates should have a single source of truth for events and properties.

**Comment by benjackwhite** [comment]
I think at the time there was a back and forth with customers and we agreed having a dedicated name was better (with a view to eventually moving the iOS and Android over with a breaking major version change). But that was a long time ago so my memory may be hazy

**Comment by marandaneto** [comment]
Yeah, I imagine filtering events/creating insights would be easier with its active event.
Can consider it for the next major though.

**Comment by marandaneto** [comment]
We'll address that on the Android/iOS version instead in the next major.
