### ISSUE TITLE
Touch events might be off sometimes depending on the view tree

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-js-lite#145]
### Description

The PH RN SDK uses [heuristics](https://github.com/PostHog/posthog-js-lite/blob/1e7bd5dd2e7b774987e99af1591ecd44bc6fac75/posthog-react-native/src/autocapture.tsx#L42) to find the touched view and its view tree, [docs](https://posthog.com/docs/libraries/react-native#autocapture).

For example, a touch called `NativeViewGestureHandler` is useless since you have no idea where it happened.

An alternative is to provide a wrapper for the [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/) library which has better touch support and is deterministic.

**Comment by steffanlevet** [comment]
For completeness, this issue has been resolved now. FYI @marandaneto
