### ISSUE TITLE
Posthog node crashes in cloudflare environment

### ISSUE THREAD

**Issue by maxprilutskiy** [PostHog/posthog-js-lite#151]
## Bug description

I'm trying to use posthog in remixjs / cloudflare pages, but it fails to create an instance of PostHog. Feels like it's trying to use axios under the hood? That's especially weird, since I'm explicitly passing it "fetch" defined globally.

Thoughts?

Am I doing something wrong?

## How to reproduce

```
import { PostHog } from 'posthog-node'

export default function getPosthogServer(env: any) {
  return new PostHog(env.POSTHOG_API_KEY, {
    host: 'https://eu.posthog.com',
    fetch: fetch,
    // enable: env.NODE_ENV === 'production',
  })
}
```

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [x] posthog-node
- [ ] posthog-react-native

**Comment by marandaneto** [comment]
@maxprilutskiy `axios` is only used if the `fetch` isn't provided, what's the version of the Node SDK?
