### ISSUE TITLE
Upgrade target to es2020

### ISSUE THREAD

**Issue by hansottowirtz** [PostHog/posthog-js-lite#163]
## Is your feature request related to a problem?

All built files are targeted es5, which compiles all `async/await` calls to some "polyfilled" version. This makes debugging PostHog quite hard as the stack traces are not complete. `async/await` has been supported for a long time and only breaks in IE11. Could I submit a PR upgrading the tsconfig.json to use es2020?

## Related sub-libraries

- [x] All of them
- [ ] posthog-web
- [ ] posthog-node
- [ ] posthog-react-native

**Comment by marandaneto** [comment]
@hansottowirtz good call, you can either wait for https://github.com/PostHog/posthog-js-lite/pull/189 to be merged on the main branch or make a PR on top of it, since it is a new major version, we are fine doing this change, thanks btw.
