### ISSUE TITLE
Session recording for mobile apps

### ISSUE THREAD

**Issue by MrSnoozles** [PostHog/posthog-js-lite#19]
Just a question to evaluate if Posthog is right for us: is it planned to support session recording for mobile apps, either via the Android/iOS SDK or this library?

**Comment by benjackwhite** [comment]
We would like this in the long term for sure, but currently mobile apps aren't supported.

**Comment by MrSnoozles** [comment]
Thank you

**Comment by bmbshlly** [comment]
can we have tentative dates?

**Comment by leckie** [comment]
This is marked as completed but the website still states this isn't supported. Which is it?

**Comment by benjackwhite** [comment]
It was closed by the submitter - not completed 😉 We don't use github issues or anything to indicate feature completeness.

We paused work on the mobile session replay as we didn't have the resources to dedicate to doing it _right_. We are actively solving this problem though but can't really commit to any timeframe.

**Comment by leckie** [comment]
Thanks so much @benjackwhite. Really appreciate you replying to this so quickly.
