### ISSUE TITLE
SvelteKit on Cloudflare requests not flushed

### ISSUE THREAD

**Issue by Pelps12** [PostHog/posthog-js-lite#190]
## Bug description

I am using SvelteKit deployed on Cloudflare Pages. I try to log server side events but get a debug message for the capture but never for the flush and shutdown

![Screenshot 2024-02-23 232804](https://github.com/PostHog/posthog-js-lite/assets/31068338/406cacb2-d0cf-4fee-8bb9-861f00c832ce)

My server side posthog client is as follows

```js
import { PUBLIC_POSTHOG_KEY, PUBLIC_URL } from '$env/static/public';
import { PostHog } from 'posthog-node';

const client = new PostHog(PUBLIC_POSTHOG_KEY, {
	flushAt: 1,
	flushInterval: 0,
	disableGeoip: false,
	fetch: fetch,
	enable: !PUBLIC_URL.includes('localhost') && !PUBLIC_URL.includes('dev')
});

client.debug(true);

export default client;
```

## Environment
@sveltejs/kit 2.5.0
@sveltejs/adapter-cloudflare 4.1.0
posthog-node 3.6.3

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [X] posthog-node
- [ ] posthog-react-native

**Comment by marandaneto** [comment]
@benjackwhite maybe https://github.com/PostHog/posthog-js-lite/pull/191 will help?
Seems like the `flush` was never called or the queue was still 0.

**Comment by Pelps12** [comment]
Is there a way I can check that to narrow down the scope of the problem?

**Comment by marandaneto** [comment]
> Is there a way I can check that to narrow down the scope of the problem?

We're going to release the first preview of the new major version, then you can test it out again, https://github.com/PostHog/posthog-js-lite/pull/191 and some other improvements should have helped.

**Comment by marandaneto** [comment]
@Pelps12 https://www.npmjs.com/package/posthog-node/v/4.0.0-beta.1

**Comment by marandaneto** [comment]
https://www.npmjs.com/package/posthog-node/v/4.0.0-beta.2 should also help, check the [changelog](https://github.com/PostHog/posthog-js-lite/blob/main/posthog-node/CHANGELOG.md) in case you need to do a migration from v3 to v4.
Closing this as possibly fixed, let us know if that's not the case.
