### ISSUE TITLE
iOS device info missing

### ISSUE THREAD

**Issue by FabianTrain** [PostHog/posthog-js-lite#201]
## Bug description

I added PostHog to my react-native project using `PostHogProvider`. After one week of data collection it looks like autocapture does not detect the iOS device info (check screenshot below). Android and other events are captured correctly. 

```Javascript
<PostHogProvider
      apiKey={Config.POSTHOG_API_KEY}
      options={{
         host: 'https://app.posthog.com',
       }}
    autocapture={{}}>
                <AppStack />
</PostHogProvider>
```

<img width="1193" alt="image" src="https://github.com/PostHog/posthog-js-lite/assets/123388349/381c89af-cecf-4974-8a0a-ad44dfd74f99">

## How to reproduce

I followed the official installation guide using `PostHogProvider` and `autocapture`.

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [X ] posthog-react-native

## Additional context

```Javascript
"dependencies": {
    "posthog-react-native": "^2.11.4",
    "react": "18.2.0",
    "react-native": "0.73.4",
   ...
  },
```

**Comment by marandaneto** [comment]
@FabianTrain Hi, do you receive events from the iOS app or is it just the device info missing? can you share the link to your organization? feel free to open a ticket on our support page or ask here https://posthog.com/questions if you don't feel comfortable sharing it here.

**Comment by marandaneto** [comment]
@FabianTrain events 2 weeks ago had this information (SDK v2.11.4).
The last events with the SDK v2.11.6, but [nothing changed](https://github.com/PostHog/posthog-js-lite/blob/main/posthog-react-native/CHANGELOG.md) about that.
The PostHog SDK uses those libraries to collect device information: if Expo app `expo-device`, or `react-native-device-info`, did you remove or upgrade something with those libs in the latest versions?

**Comment by FabianTrain** [comment]
@marandaneto Thank you for the support. I think I deployed the App to the AppStore without the pods for react-native-device-info.
