### ISSUE TITLE
cant fetch payload when using memory with posthog-react-native on web

### ISSUE THREAD

**Issue by sirpy** [PostHog/posthog-js-lite#213]
## Bug description
using persistence memory on web using the react-native package
calling useFeatureFlagWithPayload returns undefined for payload

- [x] posthog-react-native

**Comment by marandaneto** [comment]
Hi @sirpy which version of the RN SDK? Can you share your SDK init code snippets?

**Comment by benjackwhite** [comment]
It will always return undefined at first until the SDK has had the chance to call for the feature flags at which point it will return the value via a useEffect update. Are you not seeing it at all?

**Comment by marandaneto** [comment]
If that is the issue, you can [bootstrap](https://posthog.com/docs/libraries/react-native#bootstrapping-flags) the flags.
or for example, disable `preloadFeatureFlags`, but call [reloadFeatureFlagsAsync](https://posthog.com/docs/libraries/react-native#reloading-flags) and await its results.

**Comment by sirpy** [comment]
@benjackwhite yeah the useEffect doesnt kick in, the value is always undefined
@marandaneto using the latest one and nothing special in the Provider init code

**Comment by marandaneto** [comment]
@sirpy can you provide a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)? I have a sample app and everything works fine, maybe it's something in the setup or else.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
