### ISSUE TITLE
New feature flags default to false on active users

### ISSUE THREAD

**Issue by filipef101** [PostHog/posthog-js-lite#215]
## Bug description

Newly introduced feature flags will default to false instead of undefined for active users.
If we introduce a new feature, and, do a fresh login/install, it will be undefined. 
Ideally if it's not a known FF the client library should default to undefined as implied by docs.

## How to reproduce

Active user:
1. Have an active user
2. Introduce a new FF, set it to true, ie for 100% of users
3. Actual: first load, FF is false
4. **Expected: first load FF is undefined**

New user:
1. Introduce a new FF, set it to true, ie for 100% of users
2. Have a new user
3. Actual/expected: first load FF is undefined

## Related sub-libraries

- [x] All of them
- [ ] posthog-web
- [ ] posthog-node
- [ ] posthog-react-native

## Additional context

https://github.com/PostHog/posthog-js-lite/blob/1cfbf955b4dd1dbb1a799936ac34233813c7a1b4/posthog-core/src/index.ts#L1160

Not sure if can be fixed, especially if client doesn't know the existing feature flags

**Comment by marandaneto** [comment]
`undefined` is only returned if feature flags are not loaded or errored out, see [docs](https://posthog.com/docs/libraries/react-native#method-2-loading-the-flag-directly).
if you always need fresh feature flags, you can reload the flags manually, see [docs](https://posthog.com/docs/libraries/react-native#reloading-flags) or even bootstrap flags with initial/default values in case that makes more sense, see [docs](https://posthog.com/docs/libraries/react-native#bootstrapping-flags).

It's working as intended although I understand the confusion.
@neilkakkar is that a recurring problem? wondering if we could improve the UX-API in the future.

**Comment by neilkakkar** [comment]
Not really, but curious to hear more about your use case here Filipe? Why do you want undefined here for new flags? Is there some logic relying on this?

**Comment by filipef101** [comment]
Feature flagging an existing feature, on FF creation it starts as true, and later we will disable it. Didn't want to call it "featureXDisabled" instead of "featureX" for consistency etc.

So, we want the feature to be off, only if we have set it to false, not when it's unset/undefined/unknown

I worked around this by using/expecting a payload.

**Comment by filipef101** [comment]
// the response is undefined if the flags are being loaded
Seems this will only ever happen 1 time, the very first time post hog is initialized, after that as long cache exists its never going to be undefined. So maybe this makes sense, 1 line fix 😃

**Comment by neilkakkar** [comment]
Thanks for explaining!

I don't think we'll support this convention yet I'm afraid @filipef101 , the problem is returning undefined means there's an error to us, which is not true in this case.

In your case, this only becomes a problem when you're using a new feature flag in code that doesn't yet exist in PostHog, right? I think you can get around this by creating the flag before deploying your change? Or does something make this hard to do?

**Comment by filipef101** [comment]
That is not my use case.

Will close as I understand this is intended (although I don't agree). I can work around it by using payloads.

**Comment by filipef101** [comment]
The flag exists in PH, but an existing client/user on next load has cached FFs which doesn't  include the new one as either true or false, so it returns false

If nothing was cached, or a new/clean load. It would be undefined. (And nothing wrong with that)

**Comment by filipef101** [comment]
* as far as I could see other sdks return null or undefined instead of false for same scenario, ios, android & php at least

**Comment by marandaneto** [comment]
Android, iOS, and Flutter will always return the `defaultValue` for `getFeatureFlag` and `getFeatureFlagPayload` if feature flags are not loaded, errored out, or the flag is not found (default `null`), there's no `undefined` there.
`isFeatureEnabled` will always return `defaultValue` as well (default `false`).

So technically it's not possible to know if something happened or if the flag is not found.
The difference is that flags are cached, so most of the time existing flags will return its values.

**Comment by filipef101** [comment]
@marandaneto 
They return false if feature flag exists and user doesn't match criteria
They return null if feature flag is unknown
(Wether cached or not)

Posthog core returns false for a new or unknown flag when there is cached feature flags

**Comment by marandaneto** [comment]
I was talking about the other SDKs since you mentioned they have similar behavior but they don't since undefined does not apply/exist there.
