### ISSUE TITLE
Infinite render loop on useFeatureFlag.ts

### ISSUE THREAD

**Issue by filipef101** [PostHog/posthog-js-lite#218]
## Bug description

https://github.com/PostHog/posthog-js-lite/blob/7e7f8dadd3aa73d9b24929280a85102af8945c48/posthog-react-native/src/hooks/useFeatureFlag.ts#L12

Likely missing dependency on useEffect?

Not sure how I only get it some times

## How to reproduce
Not sure, might be after not opening the app for a while 🤔 
Also doesn't seem to be affecting production, or at least not getting live reports
Only saw during development

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

**Comment by filipef101** [comment]
<img width="475" alt="image" src="https://github.com/PostHog/posthog-js-lite/assets/18123246/ff3be77a-47bf-4c93-9fe5-fc67ea8b5f44">

**Comment by marandaneto** [comment]
Hi @filipef101 
Yeah I cannot reproduce this issue either, how often do you run into this issue? maybe something with hot reload?

**Comment by filipef101** [comment]
Randomly saw this on dev mode, I've since migrated to using own listeners to avoid this. I'll close since I can't reproduce
