### ISSUE TITLE
React Native app tested with jest fails with: PostHog: No storage available. Please install expo-filesystem or react-native-async-storage OR implement a custom storage provider.

### ISSUE THREAD

**Issue by itsramiel** [PostHog/posthog-js-lite#231]
## Bug description
`posthog-react-native` fails when tested with jest. This was [an issue](https://github.com/PostHog/posthog-js-lite/issues/143) before, but seems to have regressed

## How to reproduce

1. git clone https://github.com/itsramiel/posthog-repro
2. cd posthog-repor
3. yarn
4. yarn test 

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

**Comment by marandaneto** [comment]
@itsramiel did you try this out?

**Comment by itsramiel** [comment]
> @itsramiel did you try this out?

Oops forgot to reply. Yes that was my workaround anyway since it was already mentioned in the [previous issue](https://github.com/PostHog/posthog-js-lite/issues/143#issuecomment-1864428053), but I thought it was a regression since it was handled internally after the creation of that issue.

If that's the solution going forward, then alright

**Comment by marandaneto** [comment]
Gotcha, yes that is the workaround until those libraries provide the implementation of the missing platforms.
