### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by devashray-jumbo** [PostHog/posthog-js-lite#242]
## Bug description
I have integrated posthog in my expo app successfully . Events are getting recored in dashboard too but when i am trying to use useFeatureFlag hook it throws an error saying undefined is not a function . Error is located in useFeatureFlag,js . Digging more into the error it says getFeatureFlag is not a function . Now this is defined in node_modules folder 

_Please describe._

## How to reproduce

1. Simply try using useFeatureFlag hook in your component
2. Pass the feature flag in the hook
3.The app will crash 

## Related sub-libraries
- [x] posthog-react-native

**Comment by marandaneto** [comment]
@devashray-jumbo Hi,
which version of the SDK are you using? Which version of RN and Expo itself?
Can you provide a few code snippets of the PostHog SDK setup? so I can check things on my end.

Thanks

**Comment by devashray-jumbo** [comment]
Hi
Please find the details below

posthog-react-native - 3.1.1
react-native - 0.71.14 expo - 48.0.21
export const projectApiKey =
'phc_cWZmmd0TLwconAucvMlzvv7Byim5iZ3ngILJmYm9VC1';
export const projectServerUrl = 'https://us.i.posthog.com';
export const posthog = new PostHog(projectApiKey, {
host: projectServerUrl,
disabled: false,
defaultOptIn: true,
sendFeatureFlagEvent: true,
preloadFeatureFlags: true,
disableGeoip: false,
captureNativeAppLifecycleEvents: true,
});
export const logPosthogEvent = ({
eventName,
eventAttribute = {},
}: {
eventName?: string;
eventAttribute?: any;
}) => {
if (eventAttribute) {
posthog.capture(eventName, { ...eventAttribute });
return;
}
posthog.capture(eventName);
};

**Comment by devashray-jumbo** [comment]
When using feature flag hook the app crashes throwing error "undefined is
not a function"

import { useFeatureFlag } from 'posthog-react-native'
const testFlag = useFeatureFlag('Test')

**Comment by marandaneto** [comment]
@devashray-jumbo If you wanna use the `usePostHog`, `useFeatureFlag`, and other hooks, you need to set up PostHog with the [PostHogProvider](https://posthog.com/docs/libraries/react-native#with-the-posthogprovider) otherwise the hooks won't know about your`posthog` instance, or at least do [this](https://posthog.com/docs/libraries/react-native#without-the-posthogprovider).

```
export function MyApp() {
  return <PostHogProvider client={posthog}>{/* Your app code */}</PostHogProvider>
}
```
 
If you don't wanna use the `PostHogProvider`, then for instance of using the hooks, just use the `posthog.getFeatureFlag(...)` and similar methods.

**Comment by devashray-jumbo** [comment]
Hi Manoel Aranda Neto ,
I tried using the Provider as mentioned , but as soon as I used usePostHog
hook , the app crashes saying undefined is not a function.

Digging into the issue , I found out that the getAppProperties function is
causing the issue. If I go into the posthog-react-native package in
node_modules and remove this method getAppProperties , the SDK works fine
in that case.

FYI , i have installed all the other dependency which were mentioned in the
docs
[image: image.png]

Please find the code snippet below
<Provider store={store}>
<APIProvider>
<PostHogProvider
apiKey={projectApiKey}
options={{
host: projectServerUrl,
disabled: false,
defaultOptIn: true,
sendFeatureFlagEvent: true,
preloadFeatureFlags: true,
disableGeoip: false,
captureNativeAppLifecycleEvents: true,
}}
>
<RootLayoutNav />
</PostHogProvider>
</APIProvider>
</Provider> In Login Component I am using the usePostHog hook
const posthog = usePostHog();

**Comment by marandaneto** [comment]
@devashray-jumbo hey,
`getAppProperties` cannot return null or undefined so it's very strange.

We are using this in our samples and I just tested it out and everything is working fine.

The code snippets are incomplete so I cannot spot the issue besides that you are wrapping `PostHogProvider` with other things I don't know such as `Provider`, `APIProvider`, etc, you are probably trying to use `usePostHog` even before the `PostHogProvider` is created.

`PostHogProvider` must be ideally the root so it's created before anything.

Can you provide a minimal reproducible example? Just create a sample app from scratch and try to add PostHog, so you can demonstrate the bug or find out that there's something off in your implementation.

Thanks.

Best,
Manoe,

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
