### ISSUE TITLE
Does not work in Next.js serverless (API route)

### ISSUE THREAD

**Issue by antoinerousseau** [PostHog/posthog-js-lite#255]
## Bug description

SSR support was supported in https://github.com/PostHog/posthog-js-lite/pull/57), but as mentioned [here](https://github.com/PostHog/posthog-js-lite/pull/57#discussion_r1491381624), the web version gets loaded instead of the Node.js version, and it tries to access the `window` object, throwing a `ReferenceError: window is not defined` from [here](https://github.com/PostHog/posthog-js-lite/blob/main/posthog-web/src/posthog-web.ts#L22), [here](https://github.com/PostHog/posthog-js-lite/blob/main/posthog-web/src/posthog-web.ts#L53) or [here](https://github.com/PostHog/posthog-js-lite/blob/main/posthog-web/src/posthog-web.ts#L71).

## How to reproduce

1. Create a [Next.js app router API route](https://nextjs.org/docs/pages/building-your-application/routing/api-routes)
2. 
```js
import { PostHog } from "posthog-js-lite"
export async function GET() {
  const posthog = new PostHog(...)
  posthog.capture(...)
}
```
3. Call the API route from a component: you get a `ReferenceError: window is not defined`

## Related sub-libraries

- [ ] All of them
- [x] posthog-web
- [x] posthog-node
- [ ] posthog-react-native

## Additional context

Related: https://github.com/PostHog/posthog-js-lite/issues/67#issuecomment-1488735973

**Comment by benjackwhite** [comment]
This lib really isn't designed for the use case in mind. Next-js router API is running server side and as such is basically a node-js environment and so should use the built `posthog-node` target instead as that way it includes concepts such as graceful shutdown and the correct fetch implementation for your node environment.
