### ISSUE TITLE
RN Session replay plugin isn't starting a new recording after app restart

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-js-lite#268]
## Bug description

Context https://github.com/PostHog/posthog/issues/13269#issuecomment-2363950067
This is by design but I understand why it isn't obvious.
On RN, the session only rotates if the app is inactive for more than 30 minutes, and the session ID survives app restart which is different than Android and iOS.
Changing this would break the behavior of people who rely on this for session durations.
So we have a few options here, change the behavior and break compatibility, add a flag to opt in to the new behavior, or else.

## How to reproduce

1.
2.
3.

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [X] posthog-react-native

**Comment by marandaneto** [comment]
cc @chasem-dev
https://github.com/PostHog/posthog-js-lite/releases/tag/posthog-react-native-v3.3.0

**Comment by chasem-dev** [comment]
I found where it looks like you exposed the variable:
https://github.com/PostHog/posthog-ios/commit/501cc8e48991747391240475e9c8cc341e995b08

It seems like the version bump maybe wasn't picked up in a release?
https://github.com/PostHog/posthog-ios/commit/333ca7fa6d5072b1fa12f93226c2e8ea153f3b45

**Comment by marandaneto** [comment]
@chasem-dev have you upgraded your pods? Try to clean and install your pods, the session replay plugin uses the iOS SDK

**Comment by chasem-dev** [comment]
@marandaneto That worked! I ran `cd ios` and then did pod update. Testing things out now. Sorry for the false alarm! Thanks for the help
