### ISSUE TITLE
No session recordings on iOS after install per docs in Expo 50 project

### ISSUE THREAD

**Issue by jaronheard** [PostHog/posthog-js-lite#270]
## Bug description

I followed the docs to install in my project using Expo 50. I have session recording enabled in my project (web recordings come through), and iOS event tracking also works.

However, no session recordings are coming through on iOS (haven't tested Android). 

[PR with installation](https://github.com/jaronheard/soonlist-turbo/pull/216/files)

I didn't see minimum versions documented for Expo/React Native so I wonder if it's a version issue. Happy to run through any tests or look at logs.

## How to reproduce

Unsure of what minimum repro would look like here but happy to follow up with one.

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [ ] posthog-node
- [x] posthog-react-native

## Additional context

Here are my session recording settings
![image](https://github.com/user-attachments/assets/aeb13843-efe6-4ef8-8d35-77ce7eacadad)

And my [project on posthog](https://us.posthog.com/project/45506/replay/home)
#### _Thank you_ for your bug report – we love squashing them!

Very excited for these React Native session recordings in Posthog and hoping that I can get them working!

**Comment by marandaneto** [comment]
@jaronheard thanks for the report, allow me some time to investigate this, I've not tested with an Expo project tbh.

**Comment by marandaneto** [comment]
@jaronheard what is the error you get when you start your app?

>  ERROR  PostHog Debug Session replay failed to start: Error: The package 'posthog-react-native-session-replay' doesn't seem to be linked. Make sure:

Is it the same?

To see the logs, you can call `posthog.debug(true)` after creating your `posthog` instance.

**Comment by marandaneto** [comment]
The first thing I noticed is that https://github.com/PostHog/posthog.com/pull/9428
Use dev builds instead of Expo go, is that your case @jaronheard ?

**Comment by marandaneto** [comment]
<img width="770" alt="Screenshot 2024-09-25 at 10 44 24" src="https://github.com/user-attachments/assets/5176b085-cbb0-44b4-b709-202527e269e8">

Works normally if using dev builds.

**Comment by jaronheard** [comment]
hi @marandaneto! i did get this error, which gave me the cue in that i needed a new build, after which the error was resolved.
> ERROR PostHog Debug Session replay failed to start: Error: The package 'posthog-react-native-session-replay' doesn't seem to be linked. Make sure.

i was using a dev build, not expo go.

could have avoided this by a lil improvement to the docs to note that this affects native code and requires a rebuild. when i see `npx expo install ...` or a note about native dependencies i'll rebuild, otherwise by assumption is it doesn't effect the native code and require a rebuild.

thanks a milli!

**Comment by marandaneto** [comment]
Cool, thanks, I added a troubleshooting section to this PR https://github.com/PostHog/posthog.com/pull/9428 and will update the logging as well.
