### ISSUE TITLE
(React Native) posthog.identify types do not match docs

### ISSUE THREAD

**Issue by CallumHemsley** [PostHog/posthog-js-lite#312]
## Bug description
[Docs](https://posthog.com/docs/libraries/react-native#identifying-users) contain the following example:
```js
posthog.identify('distinctID', 
  { // userProperties:
      email: 'user@posthog.com',
      name: 'My Name'
  },
  { // userPropertiesSetOnce:
      date_of_first_log_in: '2024-03-01'
  }
)
```
However, I can see the posthog types from `posthog-react-native` for identity is: ```identify(distinctId?: string, properties?: PostHogEventProperties, options?: PostHogCaptureOptions): void;```

I guess aside from updating the docs, how can we achieve the userPropertiesSetOnce in RN, or is it just the types that are broken? 

## How to reproduce

1. install latest version following docs e.g `npx expo install posthog-react-native expo-file-system expo-application expo-device expo-localization`
2. See in package json you have `"posthog-react-native": "^3.3.13",`
3. Call `usePostHog` with following code below, and right click into types for identify

```js
import { usePostHog } from "posthog-react-native";
import {
  PostHogCaptureOptions,
  PostHogEventProperties,
} from "posthog-react-native/lib/posthog-core/src";

export const useAnalytics = () => {
  const posthog = usePostHog();

  const capture = (
    event: string,
    properties?: {
      [key: string]: unknown;
    },
    options?: PostHogCaptureOptions,
  ) => {
    posthog?.capture(event, properties);
  };

  const identify = (
    distinctId?: string,
    properties?: PostHogEventProperties,
    options?: PostHogCaptureOptions,
  ) => {
    // posthog?.identify(distinctId, properties, options);
    posthog.identify(
      "distinctID",
      {
        // userProperties:
        email: "user@posthog.com",
        name: "My Name",
      },
      {
        // userPropertiesSetOnce:
        date_of_first_log_in: "2024-03-01",
      },
    );
  };

  return { capture, identify };
};
```

## Related sub-libraries

- [X] posthog-react-native

**Comment by marandaneto** [comment]
Hello @CallumHemsley thanks for this issue
The `identify` method does not have support for the `userPropertiesSetOnce` ($set_once) option, I'm gonna fix that.
https://posthog.com/docs/libraries/react-native#set_once

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-js-lite/pull/313
