### ISSUE TITLE
How to get feature flag variants in react-native?

### ISSUE THREAD

**Issue by MoSattler** [PostHog/posthog-js-lite#34]
I would like to get feature-flag variants in react native. 

- `getFeatureFlags()` seems to only return an array of flag names (even though the typing indicates otherwise). 
- `getFeatureFlag()` does not seem to work at all and only returns `false`, no matter if a flag is set or not.

**Comment by benjackwhite** [comment]
Feature flags are not necessarily available on initial load. We have a special hook for this which helps take care of reacting to when the feature flags are loaded via the api request to the decide endpoint. If you call these functions directly you probably want to ensure the flags have been succesfully loaded first.

Have you followed [the docs here](https://posthog.com/docs/integrate/client/react-native#feature-flags)?

**Comment by neilkakkar** [comment]
Also, if you want flags to be instantly available, you can bootstrap them: https://posthog.com/docs/integrate/client/react-native#bootstrapping-flags
