### ISSUE TITLE
posthog-node uses shared context...

### ISSUE THREAD

**Issue by j** [PostHog/posthog-js-lite#56]
`posthog-node` uses a shared client and each client is expected to be instantiated per user (just how the browser expects it), however in the case of node, judging from what I see in code, identify calls set the dictinctID in the shared context then when a flush happens, they'll get the last called identify call.

I.E. Two requests come in at the same time, `identify(1)` and `identify(2)` comes right before flush, the payloads are then all built using ID = 2.

So I think to get it to work, every where an internal method is called, you need to create a new instance of PostHog, but I don't think this is expected.

**Comment by neilkakkar** [comment]
Hey @j , this makes sense, thanks for raising, I'd put this as the next priority on my queue!

**Comment by j** [comment]
@neilkakkar Sugestion:

`posthog-core` shouldn't have any user specific dependencies stored anywhere within the instance.

Perhaps every call should expect all properties without any fluff.  `posthog-js` can store local state to save user ids, etc. `posthog-node` should expect all properties for all calls.

**Comment by neilkakkar** [comment]
Yep, that's exactly what I'm going to do

**Comment by benjackwhite** [comment]
Currently this _shouldn't_ be how it works. Before each call we "reInit" the shared core with the new distinctId ([see here](https://github.com/PostHog/posthog-js-lite/blob/master/posthog-node/src/posthog-node.ts#L111)).

So currently the Node implementation does extra work to ensure the core always has the correct distinctId without triggering multiple events. _That said_ it does make sense for us to move to having the core be "stateless" and instead have the web/react-native libs implement a stateful version of the core that keeps track of these things.

**Comment by neilkakkar** [comment]
Hmm, even with `reInit` there's a few cases where it can get borked I think:

`capture(1)` comes in, reInits the distinct ID, and before it can create the payload [on this line](https://github.com/PostHog/posthog-js-lite/blob/955c71de191f4e8b4a4b17b439dfc4e51587ef41/posthog-core/src/index.ts#L276), `capture(2)` comes in, reinits to distinct id 2, and changes the distinct ID here: https://github.com/PostHog/posthog-js-lite/blob/955c71de191f4e8b4a4b17b439dfc4e51587ef41/posthog-core/src/index.ts#L178, thus making the `1` event into a `2` event.

**Comment by j** [comment]
@benjackwhite Yeah, I know the node client attempts to keep calls synchronized but it's very prone to errors or mess ups if there is a missed clearing of something.  Stateless for the core is definitely the way to go.  If you do need a more stateful version (browser, mobile, app, etc), you could create a `posthog-core/stateful` type client.

The biggest thing for me was having to dig into the packages to see potential edge cases and I'm sitting around sort of scratching my head wondering if it could potentially leak into other concurrent calls.  It's what `async_hooks` is for in Node.js (please don't use it ;)).

**Comment by j** [comment]
Bummer that this didn't make it to v2.0.  Currently sending events manually but wanting to get to feature flags so will have to replicate that.  I don't trust a shared context within a server environment.

**Comment by j** [comment]
> Hmm, even with `reInit` there's a few cases where it can get borked I think:
> 
> `capture(1)` comes in, reInits the distinct ID, and before it can create the payload [on this line](https://github.com/PostHog/posthog-js-lite/blob/955c71de191f4e8b4a4b17b439dfc4e51587ef41/posthog-core/src/index.ts#L276), `capture(2)` comes in, reinits to distinct id 2, and changes the distinct ID here:
> 
> https://github.com/PostHog/posthog-js-lite/blob/955c71de191f4e8b4a4b17b439dfc4e51587ef41/posthog-core/src/index.ts#L178
> 
> , thus making the `1` event into a `2` event.

Not only is that possible, but for any contributors to this library, it makes it VERY fragile and hard to understand.  Also, someone can come in and add a reInit somewhere in the pipeline and clear everything before creating a payload, or if someone comes in and adds an async call anywhere then the next request can beat it and change the other payloads.

It's become pretty frustrating working with this at scale but I just do not trust a library that has shared global state.
