### ISSUE TITLE
posthog-node v2.3.0 imports types from posthog-core without a dependency

### ISSUE THREAD

**Issue by simon-abbott** [PostHog/posthog-js-lite#65]
## Bug description

posthog-node v2.3.0 updated the types to import from `posthog-core/src`, but `posthog-core` is not listed as a dependency. This causes typescript builds to fail with the error "Cannot find module 'posthog-core/src' or its corresponding type declarations"

https://github.com/PostHog/posthog-js-lite/blob/6c6b01f2fab36973d9db3bfe727177a9c45297ef/posthog-node/src/types.ts#L1

## How to reproduce

1. Install `posthog-node`
2. Try to build with typescript

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [x] posthog-node
- [ ] posthog-react-native

**Comment by EDsCODE** [comment]
Thanks for the heads up! Working on this now

**Comment by EDsCODE** [comment]
This should be fixed now!

**Comment by simon-abbott** [comment]
That seems to have worked!
