### ISSUE TITLE
[Docs] Update Node docs to include info about requestTimeout option

### ISSUE THREAD

**Issue by frazerpoggio** [PostHog/posthog-js-lite#68]
Hi, 

I ran into an issue where the default timeout for requesting feature flags was too high. I first tried to look for information on the configuration in the [official docs](https://posthog.com/docs/integrate/server/node) but couldn't see any. I had to go find it in the source code [here](https://github.com/PostHog/posthog-js-lite/blob/744e8c56cf822f7fd72972b8a0a91f6150fd80c1/posthog-node/src/posthog-node.ts#L22). Since all the other configurations are in the official docs i figured this one got missed.

Thanks!

**Comment by benjackwhite** [comment]
Happy to do so 👍 

As a small note, you can also propose PRs to our public webpages - theirs even an "edit" icon on the page that will link you straight there. Not an expectation of course, but sometimes it's the same effort as creating an issue and is likely to get seen and fixed quicker 🙌

**Comment by benjackwhite** [comment]
[PR here](https://github.com/PostHog/posthog.com/pull/5278) so will close this pre-emptively
