### ISSUE TITLE
"Error: Maximum call stack size exceeded in execute function"

### ISSUE THREAD

**Issue by ATobolsky** [PostHog/posthog-js-lite#93]
## Bug description

The code is causing a maximum call stack size exceeded error.

## How to reproduce

1. Load the code that contains the execute function.
2. Call the execute function passing an array of SnippetArrayItem and thisArg as parameters.
3. The code will get stuck in an infinite loop, eventually throwing the RangeError: Maximum call stack size exceeded error.

## Related sub-libraries

- [ ] All of them
- [x] posthog-web
- [ ] posthog-node
- [ ] posthog-react-native

## Additional context
The error is occurring in the execute function, which contains a loop that calls itself recursively. This is causing the stack to fill up until it reaches the maximum size allowed by the browser, resulting in the error.

**Comment by benjackwhite** [comment]
With the current amount of context there isn't much we can advise here. If you can provide more context and code snippets then feel free to re-open.
