### ISSUE TITLE
Can't await captures with `sendFeatureFlags`

### ISSUE THREAD

**Issue by hansottowirtz** [PostHog/posthog-js-lite#99]
## Bug description

Normally, this works:

```ts
posthog.capture({
  distinctId,
  event: "Purchase"
});
await posthog.flushAsync()
```

but this doesn't work (flushAsync doesn't flush this capture):

```ts
posthog.capture({
  distinctId,
  event: "Purchase",
  sendFeatureFlags: true
});
await posthog.flushAsync()
```

because `super.getFeatureFlagsStateless` is not waited-on on this line:

https://github.com/PostHog/posthog-js-lite/blob/32d74d2642168325a10cb1f9a6eab4f7a75ff0b8/posthog-node/src/posthog-node.ts#L106-L107

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [x] posthog-node
- [ ] posthog-react-native

**Comment by marandaneto** [comment]
There were a few improvements discussed [here](https://github.com/PostHog/posthog-js-lite/pull/177/) that might help with this issue, I don't think we need to make everything async but `flushAsync` should be able to send everything pending regardless of calling `capture` or just using `sendFeatureFlags`.

**Comment by neilkakkar** [comment]
oh, I think I fixed this here: https://github.com/PostHog/posthog-js-lite/pull/149 - didn't realise you had already mentioned the issue! 🤦

**Comment by neilkakkar** [comment]
Feel free to comment if this isn't solved @hansottowirtz , but now we track promises being enqueued from inside sendFeatureFlags, which should make sure they are sent on shutdown, although not necessarily on the flush immediately after the capture call.
